version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/laravelblogapp/public
permissions:
  - object: /var/www/laravelblogapp/public
    owner: deployer
    group: deployer
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_services.sh
      timeout: 300
      runas: root
